name: Bug Report
description: Report a bug inside ngx-sonner
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Please search GitHub for a similar [issue](https://github.com/tutkli/ngx-sonner/issues) or [PR](https://github.com/tutkli/ngx-sonner/issues) before submitting a new issue.

  - type: textarea
    id: environment
    attributes:
      label: Please provide the environment you discovered this bug in.
      description: Please create a minimal reproduction.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true

  - type: textarea
    id: other
    attributes:
      label: Other information

  - type: checkboxes
    id: assistance
    attributes:
      label: I would be willing to submit a PR to fix this issue
      description: Assistance is provided if you need help submitting a pull request
      options:
        - label: 'Yes'
        - label: 'No'
