name: Release

on:
  workflow_dispatch:

env:
  DOCS_APP_ARTIFACT_NAME: docs
  DOCS_APP_PATH: dist/apps/docs/browser
  NODE_OPTIONS: '--max-old-space-size=6144'

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Install
        run: npm ci
      - name: Build
        run: npx nx build docs --base-href=/ngx-sonner/
      - name: Upload docs website
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: '${{ env.DOCS_APP_ARTIFACT_NAME }}'
          path: '${{ env.DOCS_APP_PATH }}'
          retention-days: 1

  deploy-docs:
    name: '[Merge] Deploy docs website'
    needs:
      - docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: '${{ steps.deploy.outputs.page_url }}'
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: |-
        ${{ github.workflow }}-deploy-docs-${{
          github.event_name == 'push'
            && github.ref
            || github.head_ref
        }}
      cancel-in-progress: "${{ github.event_name != 'push' }}"
    steps:
      - name: Download docs website
        uses: actions/download-artifact@v4
        with:
          name: '${{ env.DOCS_APP_ARTIFACT_NAME }}'
          path: '${{ env.DOCS_APP_PATH }}'
      - name: Set up GitHub Pages
        uses: actions/configure-pages@v4
      - name: Upload GitHub Pages-compatible tarball
        uses: actions/upload-pages-artifact@v3
        with:
          path: '${{ env.DOCS_APP_PATH }}'
      - name: Deploy docs website tarball
        id: deploy
        uses: actions/deploy-pages@v4

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx nx build ngx-sonner
          npx semantic-release
